servo1_min_angle: -90
servo1_max_angle: 90
servo1_min_duty: 2400
servo1_max_duty: 4800
servo2_min_angle: -90
servo2_max_angle: 90
servo2_min_duty: 2400
servo2_max_duty: 4800
servo3_min_angle: -90
servo3_max_angle: 90
servo3_min_duty: 2400
servo3_max_duty: 4800